# Docker Compose para desarrollo y producción de Cubert

version: '3.8'

services:
  # Desarrollo - Frontend y Backend separados
  cubert-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - ./backend:/app/backend:ro
      - ./client:/app/client:ro
    profiles:
      - dev

  # Producción - Binario embebido
  cubert-embedded:
    build:
      context: .
      dockerfile: Dockerfile.embedded
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    profiles:
      - prod

  # Proxy inverso (opcional para producción)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cubert-embedded
    profiles:
      - prod-nginx

# Networks
networks:
  default:
    driver: bridge

# Volumes para persistencia (si es necesario)
volumes:
  cubert_data: